//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 06:34:22 PM CET 
//


package extractCDRfeatures.corpora;

public class Pair {

    protected String id;
    protected String e2;
    protected String e1;
    protected String cid;
    protected String interaction;
    protected String type;

    
    public Pair(String id, String e1, String e2, String cid,
			String interaction, String type) {
		this.id = id;
		this.e2 = e2;
		this.e1 = e1;
		this.cid = cid;
		this.interaction = interaction;
		this.type = type;
	}

	/**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the e2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE2() {
        return e2;
    }

    /**
     * Sets the value of the e2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE2(String value) {
        this.e2 = value;
    }

    /**
     * Gets the value of the e1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE1() {
        return e1;
    }

    /**
     * Sets the value of the e1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE1(String value) {
        this.e1 = value;
    }

    /**
     * Gets the value of the ddi property.
     * 
     */
   public String getCid() {
        return cid;
    }

    /**
     * Gets the value of the ddi property.
     * 
     */
   public String getInteraction() {
        return interaction;
    }
    /**
     * Sets the value of the ddi property.
     * 
     */
    public void setCid(String value) {
        this.cid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
